name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  #Para poder dispararlo manualmente y probar.
  workflow_dispatch:
    inputs:
      reason:
        required: true
        default: Prueba
        type: string
        description: Justificación
  repository_dispatch:
    type: [export_and_branch]
env:
#edit your values here
  ENVIRONMENT_URL: 'https://org2928ffcf.crm.dynamics.com'
  CLIENT_ID: '731e4b55-60ce-4657-9633-c50d289e988f'
  TENANT_ID: 'a9515c49-4eef-4a66-ac15-2191fa5a441c'

jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@0.4.0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@0.4.0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.client_payload.solution_name }}
        solution-output-file: ${{ github.event.client_payload.solution_exported_folder}}/${{ github.event.client_payload.solution_name }}.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@0.4.0
      with:
        solution-file: ${{ github.event.client_payload.solution_exported_folder}}/${{ github.event.client_payload.solution_name }}.zip
        solution-folder: ${{ github.event.client_payload.solution_folder}}/${{ github.event.client_payload.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ github.event.client_payload.solution_folder}}/${{ github.event.client_payload.solution_name }}
        solution-target-folder: ${{ github.event.client_payload.solution_target_folder}}/${{ github.event.client_payload.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
        #Setting para hacer que haga un commit directo en el brancha ppal (main).
        branch-name: pp_branch
        
    - name: Git Merge to Main!
      run: |
        git checkout pp_branch
        git checkout main
        git merge pp_branch
        git add .
        git commit -m 'CI Merge'
        git push
  
  #Invoco el WF de release.
  Release-solution-ALMLab:
    #para evitar que corra mientras prueba de dejar la solución exportada en main
    if: github.repository == 'octo-org/octo-repo-prod'
    needs: export-from-dev
    uses: ./.github/workflows/release-solution-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: ALMLab
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://orgcd075066.crm.dynamics.com
      PRODUCTION_ENVIRONMENT_URL: https://org0a4498d4.crm.dynamics.com
      CLIENT_ID: 731e4b55-60ce-4657-9633-c50d289e988f
      TENANT_ID: a9515c49-4eef-4a66-ac15-2191fa5a441c      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}        
#prueba
